SET C51INC=D:\keil 5\C51\INC\Atmel\;D:\keil 5\C51\INC\
SET C51LIB=D:\keil 5\C51\LIB
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00B71B00
"D:\keil 5\C51\BIN\A51.EXE" @.\output\STARTUP._ia
"D:\keil 5\C51\BIN\C51.EXE" @.\output\LCD1602.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\main.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\Event_control.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\display_manage.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\Timer.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\timer_manage.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\keypad.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\Delay.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\alarm_manage.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\buzzer.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\number_input.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\menu_manage.__i
"D:\keil 5\C51\BIN\C51.EXE" @.\output\stopwatch_manage.__i
"D:\keil 5\C51\BIN\LIB51.EXE" @".\output\alarm_1.__b"
